### PR TITLE
Refactor handleRefreshAccount, handleLoginUrl, handleRedirectUrl, handleRefreshUrl

### PR DESCRIPTION
**Pull request by marcinbodnar**

### CODE REVIEW

**Comment by marcinbodnar** [comment]
@vgrichina Please let me know if you have any comments for these changes. If not I will resolve conflicts and it will be ready to merge. It affects many files and functionalities so soon there will be another conflict.

After the merge, I will be able to make changes for #349, because it affects this PR.

**Comment by vgrichina** [comment]
@marcinbodnar sorry this got off my radar. Looks good overall, but please rebase as there are conflicting changes.

**Comment by marcinbodnar** [comment]
@vgrichina conflicts resolved

**Comment by vgrichina** [comment]
@marcinbodnar looks good, but I need to make sure login / transaction signing works, so might beed some time to test and then merge

**Pull request merged**
