### PR TITLE
Fix full access keys by updating to nearlib with hotfix

### PR DESCRIPTION
**Pull request by janedegtiareva**

### CODE REVIEW

**Comment by vgrichina** [comment]
@janedegtiareva needs yarn.lock

**Comment by janedegtiareva** [comment]
> @janedegtiareva needs yarn.lock

done. 
I am confused, I though we were removing .lock files from everywhere?

**Comment by janedegtiareva** [comment]
Verified fix works on https://near-wallet-pr-134.onrender.com/

**Comment by vgrichina** [comment]
@janedegtiareva we totally shouldn't remove lock files from apps to keep deployments deterministic. Libraries is more debatable as lock file would only affect dev experience and CI.

**Comment by vgrichina** [comment]
There are some arguments to keep them for all projects though (e.g. https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/).

**Pull request merged**
