### PR TITLE
Make callback work when signing transaction

### PR DESCRIPTION
**Pull request by vgrichina**
For testing:

https://app.near.ai/app/ogrd4hurv/
https://studio.nearprotocol.com/?f=ogrd4hurv

### CODE REVIEW

**Comment by Patrick1904** [comment]
Re-direct post signing works great for me.

**Comment by kcole16** [comment]
@vgrichina Tried sending two messages back-to-back and getting a nonce error:
```
index.js:30 Error in background action: Error: Transaction nonce 2 must be larger than nonce of the used access key 2
    at i.sendJsonRpc (json-rpc-provider.js:58)
```

**Steps to reproduce:**
1. Send a message on https://app.near.ai/app/ogrd4hurv/
2. Send second message using the same account

**Comment by vgrichina** [comment]
@kcole16 try logging out and logging in, there is a known issue because of shared domain for multiple apps. 

I also assume you were sending premium, right?

**Comment by kcole16** [comment]
@vgrichina Logging out does seem to fix it. First time I sent a regular post, then a premium post (which is when I encountered the error)

**Pull request merged**
