### PR TITLE
Remove regex pattern attribute from seed phrase recovery input field

### PR DESCRIPTION
**Pull request by kcole16**
Fixes the immediate problem posed in #256, which is pretty critical. Open to suggestions on a new regex pattern.

### CODE REVIEW

**Comment by vgrichina** [comment]
hmm, I am not sure I follow why the fix works. What in the phrase wasn't matching pattern?

**Comment by kcole16** [comment]
> hmm, I am not sure I follow why the fix works. What in the phrase wasn't matching pattern?

The pattern looked fine to me, but for some reason, a large % of seed phrases don't satisfy the pattern, and return the HTML form error ```Please match the requested format```

Try to recover this account to see what I mean.

username: ```bothblockers```
seed: ```asset have fat dutch view cliff trumpet quick riot scheme toy brain```

Seems to be happening for more than ~50% of cases.

**Comment by vgrichina** [comment]
https://near-wallet-pr-267.onrender.com/recover-seed-phrase still doesn't work for me

**Comment by kcole16** [comment]
> https://near-wallet-pr-267.onrender.com/recover-seed-phrase still doesn't work for me

Are you still receiving the validation error?

**Comment by vgrichina** [comment]
> > https://near-wallet-pr-267.onrender.com/recover-seed-phrase still doesn't work for me
> 
> Are you still receiving the validation error?

No, I'm getting `Failed to recover account.` both with and without this PR.

**Comment by kcole16** [comment]
Closing this until I can figure out what's up with #256

**Pull request closed without merging**
