### PR TITLE
Recover w/link: Add confirm account page

### PR DESCRIPTION
**Pull request by Patrick1904**

### CODE REVIEW

**Comment by Patrick1904** [comment]
Forked repo from while setting up new computer and added commit. Will not use forked repo going forward.

https://github.com/nearprotocol/near-wallet/pull/361

**Comment by vgrichina** [comment]
@Patrick1904 this one is ok, but please re-create #361 using branch in nearprotocol repo.

Also please resolve conflicts in `src/components/Routing.js` here.

**Comment by vgrichina** [comment]
so if I use improper link it just redirect to Create Account and logs following message in console:
> Error: Cannot find matching public key for account some-account

I think we should handle error and show a screen which:
1) Suggests to check whether this is the link from the latest message in e-mail/SMS and if copy-pasting that whole link got copy-pasted.
2) Explains to users gently that they are out of luck if message is lost.
3) Provides an option to create new account.

@kcole16 WDYT, may you help with copy for that?

**Comment by kcole16** [comment]
> @kcole16 WDYT, may you help with copy for that?

@vgrichina Here is the latest pass:(https://www.figma.com/file/kFY8wtRYKa6jit4zxTU5Nv/email-confirmation-error?node-id=0%3A1)

Currently pretty minimal on the copy.

**Comment by vgrichina** [comment]
@kcole16 
> @vgrichina Here is the latest pass:(https://www.figma.com/file/kFY8wtRYKa6jit4zxTU5Nv/email-confirmation-error?node-id=0%3A1)

I think it might be confusing when we start burning keys already used for recovery. Like if you just clicked link in wrong message this might cause pretty big panic.

**Comment by kcole16** [comment]
@vgrichina @Patrick1904 @corwinharrell 

"If you've enabled email recovery, please check your inbox for the latest message, as all earlier messages are considered invalid. "

**Comment by vgrichina** [comment]
so the flow now handles wrong link properly when one tries to recover

https://near-wallet-pr-359.onrender.com/recover-with-link/some-account/foobar

however there are spinners displayed for some reason in top right corner (see attached)
Screen Shot 2020-02-04 at 4 48 51 PM

LGTM other than that, feel free to merge

**Pull request merged**
