### PR TITLE
Sort accounts alphabetically in dropdown

### PR DESCRIPTION
**Pull request by vgrichina**

### CODE REVIEW

**Comment by Patrick1904** [comment]
> Your [Render](https://render.com) PR Server at https://near-wallet-staging-pr-384.onrender.com is now live!
> 
> View it on your dashboard at https://dashboard.render.com/static/srv-bp28otv8jd5pf9gvqb80.

@vgrichina seems something broke? The onrender link isn't working
Screen Shot 2020-02-12 at 4 14 38 PM

**Comment by vgrichina** [comment]
@Patrick1904 sorry, messed up quick fix. Updated one should work (also re-wired some Redux stuff as `account.accounts` was confusing IMO).

**Comment by Patrick1904** [comment]
@vgrichina can we merge this? I'd like to make some changes that'll affect this code

**Comment by vgrichina** [comment]
@Patrick1904 was holding off because of hackathona

**Pull request merged**
